Don't run inductor tests
we're getting an issue with the tests:

ValueError: option names {'--shard-id'} already added

This might be due to out-of-tree tests; after some debugging attempt I'm
removing due to time constraints.

The same tests were showing a "RuntimeError: can't create new thread at interpreter shutdown" on python 3.12

This is detailed here https://github.com/python/cpython/issues/115533

From looking at the pytorch code it looks like there's still some polishing of
support for 3.12 happening so will consider this an upstream error